stages:
  train:
    cmd: python src/model.py
    deps:
    - src/model.py
    - params.yaml
    - train/train.csv
    - test/test.csv
    outs:
    - models/model.keras
    - artifacts/X_test_cnn.npy
    - artifacts/y_test.npy
    - artifacts/training_history.json
    - artifacts/feature_columns.json     # add this
    - dvclive/

  evaluate:
    cmd: python src/evaluate.py
    deps:
    - src/evaluate.py
    - models/model.keras
    - artifacts/X_test_cnn.npy
    - artifacts/y_test.npy
    - artifacts/training_history.json
    - artifacts/feature_columns.json     # add this
    - test/test.csv
    - params.yaml
    metrics:
    - metrics.json:
        cache: false
params:
- dvclive/params.yaml
metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/metrics:
    x: step
